---
nsg_config:
  rg: azure_poc_ptoal
  name: testnsg
  rules:
    - name: allow-ssh
      protocol: Tcp
      source_address_prefix: '174.109.158.0/24'
      destination_port_range: 22
      access: Allow
      priority: 1001
      direction: Inbound